const strings = {
    language: ["Language", "Lenguaje"],
    about_title: ["About", "Inicio"],
    about_blurb: [
        "Personalized vocabulary learning using sets of words. Users can create and select sets and words from our dictionary to learn interactively.", 
        "Aprendizaje de vocabulario personalizado utilizando colecciones de palabras. Como usuario, podras crear y seleccionar collectiones y palabras de nuestro diccionario para aprender de forma interactiva."
    ],
    dictionary_title: ["Dictionary", "Diccionario"],
    sets_title: ["Sets", "Collecciones"],
    set_create: ["Create set", "Crear colleccion"],
    sort: ["Sort", "Sortear"],
    sort_alphi: ["A-Z", "A-Z"],
    sort_alphd: ["Z-A", "Z-A"],
    sort_scorei: ["Score increasing", "Score"],
    sort_scored: ["Score decreasing", "Score"],
    user_title: ["Account", "Cuenta"],
    create: ["Create", "Crear"],
    user_create_text: ["Create an account", "Crea una cuenta"],
    login: ["Log in", "Entrar"],
    logout: ["Log out", "Salir"],
    login_text: ["Or log in to continue:", "O inicia una sesion para continuar:"],
    username: ["Username", "Nombre de usuario"],
    username_text: ["Enter a username", "Entra nombre de usuario"],
    passkey: ["Passkey", "Contrasena numerica"],
    passkey_text: ["Enter a passkey", "Entra contrasena numerica"],
    change_name: ["Change username", "Cambiar nombre de usuario"],
    change_name_text: ["Enter new username", "Entra nombre de usuario nuevo"],
    user_information: ["Account info", "Informacion sobre la cuenta"],
    user_date: ["Date created", "Fecha creada"],
    user_delete: ["Delete account", "Borrar cuenta"],
    update: ["Update", "Actualizar"],
    back: ["Back", "Regresar"],
    definition: ["Definition(s):", "Definicion(es):"],
    example: ["Example sentence(s):", "Ejemplo(s) de uso:"],
    search: ["Search", "Buscar"],
    delete: ["Delete", "Borrar"],
    t_success: ["Success!", "Exito!"],
    t_fail: ["Oops!", "Ups!"],
    t_login_success: ["Logged in!", "Session iniciada!"],
    t_login_fail: ["Log in failed!" , "No se pudo iniciar la session!"],
    t_logout_success: ["Logged out!", "Session cerrada!"],
    t_create_acc_fail: ["Failed to create account!", "No se pudo crear la cuenta!"],
    t_change_name_success: ["Username changed!", "Nombre de usuario cambiado!"],
    t_name_exists: ["Username is already in use!", "Nombre de usuario ya esta en uso!"],
    t_delete_acc_success: ["Account deleted!", "Cuenta borrada!"],
    t_delete_acc_fail: ["Failed to delete account!", "No se puedo borrar la cuenta!"],
    t_user_timed_out: ["User timed out!", "Session expirada!"],
    t_block_login: ["User is active in a different tab!", "Usuario esta activo en otra pestana!"]
};

export default strings