--
-- PostgreSQL database dump
--

\restrict G8GeOUyXzqCxGP06fhqD4aAb89a0H4wws4jNd7EMQX1ddm1jZrZppdPCqHqBAcJ

-- Dumped from database version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.19 (Ubuntu 14.19-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: Memorichuelas; Type: SCHEMA; Schema: -; Owner: ricar
--

CREATE SCHEMA "Memorichuelas";


ALTER SCHEMA "Memorichuelas" OWNER TO ricar;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Credits; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Credits" (
    "creditID" integer NOT NULL,
    "wordID" integer NOT NULL,
    citation character varying(500) NOT NULL
);


ALTER TABLE "Memorichuelas"."Credits" OWNER TO ricar;

--
-- Name: Definitions; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Definitions" (
    "defID" integer NOT NULL,
    "wordID" integer NOT NULL,
    definition character varying(1000) NOT NULL
);


ALTER TABLE "Memorichuelas"."Definitions" OWNER TO ricar;

--
-- Name: Definitions_defID_seq; Type: SEQUENCE; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE "Memorichuelas"."Definitions" ALTER COLUMN "defID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Memorichuelas"."Definitions_defID_seq"
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Examples; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Examples" (
    "exID" integer NOT NULL,
    "wordID" integer NOT NULL,
    example character varying(1000) NOT NULL
);


ALTER TABLE "Memorichuelas"."Examples" OWNER TO ricar;

--
-- Name: Examples_exID_seq; Type: SEQUENCE; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE "Memorichuelas"."Examples" ALTER COLUMN "exID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Memorichuelas"."Examples_exID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SetWords; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."SetWords" (
    "setID" integer NOT NULL,
    "wordID" integer NOT NULL,
    score numeric(3,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE "Memorichuelas"."SetWords" OWNER TO ricar;

--
-- Name: Sets; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Sets" (
    "setID" integer NOT NULL,
    "userID" integer NOT NULL,
    name character varying(20) NOT NULL,
    score numeric(3,2) DEFAULT 0.00 NOT NULL
);


ALTER TABLE "Memorichuelas"."Sets" OWNER TO ricar;

--
-- Name: Sets_setID_seq; Type: SEQUENCE; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE "Memorichuelas"."Sets" ALTER COLUMN "setID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Memorichuelas"."Sets_setID_seq"
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Users" (
    "userID" integer NOT NULL,
    name character varying(10) NOT NULL,
    passkey numeric(8,0) NOT NULL,
    date date NOT NULL,
    active boolean DEFAULT false NOT NULL,
    "timestamp" timestamp with time zone
);


ALTER TABLE "Memorichuelas"."Users" OWNER TO ricar;

--
-- Name: Users_userID_seq; Type: SEQUENCE; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE "Memorichuelas"."Users" ALTER COLUMN "userID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Memorichuelas"."Users_userID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Words; Type: TABLE; Schema: Memorichuelas; Owner: ricar
--

CREATE TABLE "Memorichuelas"."Words" (
    "wordID" integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE "Memorichuelas"."Words" OWNER TO ricar;

--
-- Name: Words_wordID_seq; Type: SEQUENCE; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE "Memorichuelas"."Words" ALTER COLUMN "wordID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "Memorichuelas"."Words_wordID_seq"
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Credits Credits_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Credits"
    ADD CONSTRAINT "Credits_pkey" PRIMARY KEY ("creditID");


--
-- Name: Definitions Definitions_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Definitions"
    ADD CONSTRAINT "Definitions_pkey" PRIMARY KEY ("defID");


--
-- Name: Words Dictionary_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Words"
    ADD CONSTRAINT "Dictionary_pkey" PRIMARY KEY ("wordID");


--
-- Name: Examples Examples_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Examples"
    ADD CONSTRAINT "Examples_pkey" PRIMARY KEY ("exID");


--
-- Name: SetWords SetWords_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."SetWords"
    ADD CONSTRAINT "SetWords_pkey" PRIMARY KEY ("setID", "wordID");


--
-- Name: Sets Sets_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Sets"
    ADD CONSTRAINT "Sets_pkey" PRIMARY KEY ("setID");


--
-- Name: Users Users_pkey; Type: CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("userID");


--
-- Name: Credits Credits_fkey; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Credits"
    ADD CONSTRAINT "Credits_fkey" FOREIGN KEY ("wordID") REFERENCES "Memorichuelas"."Words"("wordID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- Name: Definitions Definitions_fkey; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Definitions"
    ADD CONSTRAINT "Definitions_fkey" FOREIGN KEY ("wordID") REFERENCES "Memorichuelas"."Words"("wordID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- Name: Examples Examples_fkey; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Examples"
    ADD CONSTRAINT "Examples_fkey" FOREIGN KEY ("wordID") REFERENCES "Memorichuelas"."Words"("wordID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- Name: SetWords SetWords_fkey1; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."SetWords"
    ADD CONSTRAINT "SetWords_fkey1" FOREIGN KEY ("setID") REFERENCES "Memorichuelas"."Sets"("setID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- Name: SetWords SetWords_fkey2; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."SetWords"
    ADD CONSTRAINT "SetWords_fkey2" FOREIGN KEY ("wordID") REFERENCES "Memorichuelas"."Words"("wordID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- Name: Sets Sets_fkey; Type: FK CONSTRAINT; Schema: Memorichuelas; Owner: ricar
--

ALTER TABLE ONLY "Memorichuelas"."Sets"
    ADD CONSTRAINT "Sets_fkey" FOREIGN KEY ("userID") REFERENCES "Memorichuelas"."Users"("userID") MATCH FULL ON DELETE CASCADE NOT VALID;


--
-- PostgreSQL database dump complete
--

\unrestrict G8GeOUyXzqCxGP06fhqD4aAb89a0H4wws4jNd7EMQX1ddm1jZrZppdPCqHqBAcJ

