-- memorichuelas_schema.sql
CREATE TABLE IF NOT EXISTS Users (
	user_id bigint GENERATED BY DEFAULT AS IDENTITY,
	name character varying(10) NOT NULL,
	passkey numeric(8,0) NOT NULL,
	"date" date NOT NULL,
	active boolean DEFAULT false NOT NULL,
	"timestamp" timestamp with time zone,
	PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS Sets (
	set_id bigint GENERATED BY DEFAULT AS IDENTITY,
	name character varying(20) NOT NULL,
	official boolean DEFAULT false NOT NULL,
	PRIMARY KEY (set_id)
);

CREATE TABLE IF NOT EXISTS Words (
	word_id bigint GENERATED BY DEFAULT AS IDENTITY,
	name character varying(50) NOT NULL,
	PRIMARY KEY (word_id)
);

CREATE TABLE IF NOT EXISTS Definitions (
	def_id bigint GENERATED BY DEFAULT AS IDENTITY,
	word_id bigint NOT NULL,
	definition character varying(1000) NOT NULL,
	PRIMARY KEY (def_id),
	FOREIGN KEY (word_id) REFERENCES Words (word_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Examples (
	ex_id bigint GENERATED BY DEFAULT AS IDENTITY,
	word_id bigint NOT NULL,
	example character varying(1000) NOT NULL,
	PRIMARY KEY (ex_id),
	FOREIGN KEY (word_id) REFERENCES Words (word_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Credits (
	credit_id bigint GENERATED BY DEFAULT AS IDENTITY,
	word_id bigint NOT NULL,
	citation character varying(500) NOT NULL,
	PRIMARY KEY (credit_id),
	FOREIGN KEY (word_id) REFERENCES Words (word_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SetWords (
	set_id bigint NOT NULL,
	word_id bigint NOT NULL,
	score numeric(3,2) DEFAULT 0.00 NOT NULL,
	PRIMARY KEY (set_id, word_id),
	FOREIGN KEY (set_id) REFERENCES Sets (set_id) ON DELETE CASCADE,
	FOREIGN KEY (word_id) REFERENCES Words (word_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserSets (
	set_id bigint NOT NULL,
	user_id bigint NOT NULL,
	score numeric(3,2) DEFAULT 0.00 NOT NULL,
	PRIMARY KEY (set_id, user_id),
	FOREIGN KEY (set_id) REFERENCES Sets (set_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES Users (user_id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION del_orphan_set() RETURNS trigger AS $$
BEGIN
	DELETE FROM Sets s WHERE NOT s.official AND s.set_id = OLD.set_id
	AND NOT EXISTS(
		SELECT * FROM UserSets us WHERE us.set_id = OLD.set_id
	);
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS us_after_del ON UserSets;
CREATE TRIGGER us_after_del AFTER DELETE ON UserSets
FOR EACH ROW EXECUTE FUNCTION del_orphan_set();
